config/routes.rb
Rails.application.routes.draw do

   root 'leagues#index'

  resources :leagues do
    resources :matches
  end

end

app/models/club.rb
class Club < ActiveRecord::Base
	has_and_belongs_to_many :leagues
end

app/models/league.rb
class League < ActiveRecord::Base
	has_many :matches, dependent: :destroy
	has_and_belongs_to_many :clubs
end

app/models/match.rb
class Match < ActiveRecord::Base
	belongs_to :league
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
	def index
		@leagues = League.all
	end
	def new
		@league = League.new
	end
	def create
		@league = League.new(league_params)
		@league.save
		redirect_to leagues_path, notice: "League added successfully!! "
	end
	def update
		@league = League.find(params[:id])
		if @league.update(league_params)
			redirect_to leagues_path, notice: "League edited!! "
		end
	end
	def destroy
		@league = League.find(params[:id])
		@league.destroy
		redirect_to leagues_path, notice: "League deleted!! "	
	end
	def edit
		@league = League.find(params[:id]) 
	end

	private
	def league_params
    	params.require(:league).permit(:name, :location, :sdate, :edate)
  	end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
	def index
		@leauge = League.find(params[:league_id])
		# render plain: @leauge.matches
		@matches = @leauge.matches
	end
	def new
		@match = Match.new
		@league = League.find(params[:league_id])
	end
	def create
		@league = League.find(params[:league_id])
		@match = @league.matches.create(match_params)
		# render plain: @league.matches.create(match_params)
		# @leauge << @match
		redirect_to league_matches_path, notice: "Match added successfully!! "
	end
	def update
		@match = Match.find(params[:id])
		if @match.update(match_params)
			redirect_to league_matches_path, notice: "Match edited!! "
		end
	end
	def destroy
		@match = Match.find(params[:id])
		@match.destroy
		redirect_to league_matches_path, notice: "Match deleted!! "	
	end
	def edit
		@league = League.find(params[:league_id])
		@match = Match.find(params[:id]) 
	end

	private
	def match_params
    	params.require(:match).permit(:location, :sdate, :club1_id, :club2_id)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/league_helper.rb
module LeagueHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
<table>
  <tr>
    <td> Name </td>
    <td> <%= f.text_field :name %> </td> 
  </tr>
  <tr>
    <td> Location </td>
    <td> <%= f.text_field :location %> </td> 
  </tr>
  <tr>
    <td> Start Date </td>
    <td> <%= f.date_field  :sdate %> </td> 
  </tr>
  <tr>
    <td> End Date </td>
    <td> <%= f.date_field :edate %> </td> 
  </tr>
  <tr>
    <td>  </td>
    <td> <%= f.submit %>  </td> 
  </tr>  
</table>
<% end %>

app/views/leagues/create.html.erb
<%= @league.inspect %>

app/views/leagues/edit.html.erb
<h1> Edit League </h1>

<%= render 'form' %>

app/views/leagues/home.html.erb
<h1> Leagues </h1>
<% message = params[:message] %>
<div class='message'> <%= p message if !message.nil? %> </div>
<%= link_to 'Create a New League', new_league_path %>

<table>
	<tr>
		<th> Leagues </th>
		<th> </th>
		<th> </th>
		<th> </th>
		<th> </th>
	</tr>
	<% @leagues.each do |league| %>
	<tr>
		<td> <%= league.name %> </td>
		<td> <%= link_to 'Add Clubs' %> </td>
		<td> <%= link_to 'Add Matches' %> </td>
		<td> <%= link_to 'Edit', edit_league_path(league) %> </td>
		<td> <%= link_to 'Delete', league_path(league), method: :delete %> </td>
	</tr>
	<% end %>
</table>

app/views/leagues/index.html.erb
<h1> Leagues </h1>
 <% message = params[:message] %> 
<i> <div class='message'> <%= notice %> </div> </i> <br />
<%= link_to 'Create a New League', new_league_path %> <br /> <br />
<div class='datagrid'>
	<table class='customTable'>
		<tbody>
			<% @leagues.each do |league| %>
				<tr class='alt'>
					<td> 
						<h3> <%= league.name %> </h3> 
						<b> Location: </b> <i> <%= league.location %> </i> <br />
						<b> Date: </b> <i> <%= league.sdate %> to <%= league.sdate %> </i>
					</td>
					<td> <%= link_to 'Matches', league_matches_path(league) %> </td>
					<td> <%= link_to 'Edit', edit_league_path(league) %> </td>
					<td> <%= link_to 'Delete', league_path(league), method: :delete %> </td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div> 

app/views/leagues/new.html.erb
<h1> Create New League </h1>

<%= render 'form' %>

app/views/matches/_form.html.erb
<%= form_for @match, url: league_matches_path do |f| %>
<table>
  <tr>
    <td> Location </td>
    <td> <%= f.text_field :location %> </td> 
  </tr>
  <tr>
    <td> Start Date </td>
    <td> <%= f.date_field :sdate %> </td> 
  </tr>
  <tr>
    <td> Team 1 </td>
    <td> <%= f.text_field  :club1_id %> </td> 
  </tr>
  <tr>
    <td> Team 2 </td>
    <td> <%= f.text_field :club2_id %> </td> 
  </tr>
  <tr>
    <td>  </td>
    <td> <%= f.submit %>  </td> 
  </tr>  
</table>
<% end %>

app/views/matches/create.html.erb
<%= @league.inspect %>

app/views/matches/edit.html.erb
<h1> Edit Match </h1>

<%= form_for @match, url: league_match_path(@league, @match) do |f| %>
<table>
  <tr>
    <td> Location </td>
    <td> <%= f.text_field :location %> </td> 
  </tr>
  <tr>
    <td> Start Date </td>
    <td> <%= f.date_field :sdate %> </td> 
  </tr>
  <tr>
    <td> Team 1 </td>
    <td> <%= f.text_field  :club1_id %> </td> 
  </tr>
  <tr>
    <td> Team 2 </td>
    <td> <%= f.text_field :club2_id %> </td> 
  </tr>
  <tr>
    <td>  </td>
    <td> <%= f.submit %>  </td> 
  </tr>  
</table>
<% end %>

app/views/matches/index.html.erb
<% @league = League.find(params[:league_id])%>
<h1> <%= @league.name %> </h1>
<%= link_to 'Back To Leagues', leagues_path %>
<h2> Matches </h2>
<i> <div class='message'> <%= notice %> </div> </i> <br />
<%= link_to 'Create New Match', new_league_match_path %> <br /> <br />

<div class='datagrid'>
	<table>
		<tbody>
			<% @matches.each do |match| %>
			<tr>
				<td>
				 	<b> <%= match.club1_id %> vs. <%= match.club2_id %> </b> <br /><br />
				 	<b> Location: </b> <%= match.location %> <br />
				 	<b> Date: </b> <%= match.sdate %> 
				</td>
				<td> <%= link_to 'Edit', edit_league_match_path(@league,match) %> </td>
				<td> <%= link_to 'Delete', league_match_path(@league,match), method: :delete %> </td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/matches/new.html.erb
<h1> Create New Match </h1>

<%= render 'form' %>